using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;
using System.Diagnostics;

namespace WindowsFormsApp1
{
    class KML
    {
        string kml = "";
        string filepath = @"c:\Drone Routing\KML Files\";
        public void NewKML(List<Location> path, Graph[,,] map)
        {
            DateTime localDate = DateTime.Now;
            Location coordinates = path.First();
            
            kml = "<?xml version=\"1.0\" encoding=\"UTF - 8\"?>" +
                "\n\t< !--Generated by KMLtools -->" +
                "\n\t< kml xmlns = \"http://earth.google.com/kml/2.2\" >" +
                "\n\t< Document >" +
                "\n\n\t< name > gps2kml </ name >" +
                "\n\t< Style >< PolyStyle >< fill > 0 </ fill >< outline > 1 </ outline ></ PolyStyle ></ Style >" +
                "\n\t< Placemark >\n\t< name > 1 </ name >" +
                "\n\t< MultiGeometry >< LineString >< coordinates > ";

            for (int i = 0; i < path.Count; i++)
            {
                kml += map[path[i].x, path[i].y, path[i].z].longitude.ToString() + ", " +  map[path[i].x, path[i].y, path[i].z].latitude.ToString() + ", " + map[path[i].x, path[i].y, path[i].z].altitude.ToString() + " ";
            }
            kml += "\n\t</coordinates></LineString></MultiGeometry>" +
                "\n\t</ Placemark >" +
                "\n\t</ Document >" +
                "\n</ kml >";

            string time = localDate.ToString().Replace("/", ".");
            filepath += "Route"/* + time*/ + ".kml";

            using (FileStream fs = File.Create(filepath))
            {
                Byte[] info = new UTF8Encoding(true).GetBytes(kml);
                // Add some information to the file.
                fs.Write(info, 0, info.Length);
            }

            //Process.Start(@"c:\Drone Routing\KML Files\");
        }
    }
}
